// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string               `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	UserName             string               `protobuf:"bytes,6,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string               `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	AvatarUrl            string               `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	MoreInfo             string               `protobuf:"bytes,9,opt,name=more_info,json=moreInfo,proto3" json:"more_info,omitempty"`
	Dob                  *timestamp.Timestamp `protobuf:"bytes,10,opt,name=dob,proto3" json:"dob,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,11,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime          *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Account) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Account) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Account) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Account) GetMoreInfo() string {
	if m != nil {
		return m.MoreInfo
	}
	return ""
}

func (m *Account) GetDob() *timestamp.Timestamp {
	if m != nil {
		return m.Dob
	}
	return nil
}

func (m *Account) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *Account) GetUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type HomeRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeRequest) Reset()         { *m = HomeRequest{} }
func (m *HomeRequest) String() string { return proto.CompactTextString(m) }
func (*HomeRequest) ProtoMessage()    {}
func (*HomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{3}
}

func (m *HomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeRequest.Unmarshal(m, b)
}
func (m *HomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeRequest.Marshal(b, m, deterministic)
}
func (m *HomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeRequest.Merge(m, src)
}
func (m *HomeRequest) XXX_Size() int {
	return xxx_messageInfo_HomeRequest.Size(m)
}
func (m *HomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HomeRequest proto.InternalMessageInfo

func (m *HomeRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type HomeResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeResponse) Reset()         { *m = HomeResponse{} }
func (m *HomeResponse) String() string { return proto.CompactTextString(m) }
func (*HomeResponse) ProtoMessage()    {}
func (*HomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{4}
}

func (m *HomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeResponse.Unmarshal(m, b)
}
func (m *HomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeResponse.Marshal(b, m, deterministic)
}
func (m *HomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeResponse.Merge(m, src)
}
func (m *HomeResponse) XXX_Size() int {
	return xxx_messageInfo_HomeResponse.Size(m)
}
func (m *HomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HomeResponse proto.InternalMessageInfo

func (m *HomeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RegisterRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	AccountInfo          *Account `protobuf:"bytes,2,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{5}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RegisterRequest) GetAccountInfo() *Account {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

type RegisterResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AccountInfo          *Account `protobuf:"bytes,3,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{6}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterResponse) GetAccountInfo() *Account {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

type GetAllRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRequest) Reset()         { *m = GetAllRequest{} }
func (m *GetAllRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRequest) ProtoMessage()    {}
func (*GetAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{7}
}

func (m *GetAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRequest.Unmarshal(m, b)
}
func (m *GetAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRequest.Merge(m, src)
}
func (m *GetAllRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRequest.Size(m)
}
func (m *GetAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRequest proto.InternalMessageInfo

func (m *GetAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type GetAllResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	AccountInfo          *Account `protobuf:"bytes,2,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllResponse) Reset()         { *m = GetAllResponse{} }
func (m *GetAllResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllResponse) ProtoMessage()    {}
func (*GetAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{8}
}

func (m *GetAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllResponse.Unmarshal(m, b)
}
func (m *GetAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllResponse.Marshal(b, m, deterministic)
}
func (m *GetAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllResponse.Merge(m, src)
}
func (m *GetAllResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllResponse.Size(m)
}
func (m *GetAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllResponse proto.InternalMessageInfo

func (m *GetAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetAllResponse) GetAccountInfo() *Account {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

/// integration chat service inside profile service
type Point struct {
	Latitude             int32    `protobuf:"varint,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            int32    `protobuf:"varint,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point) Reset()         { *m = Point{} }
func (m *Point) String() string { return proto.CompactTextString(m) }
func (*Point) ProtoMessage()    {}
func (*Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{9}
}

func (m *Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point.Unmarshal(m, b)
}
func (m *Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point.Marshal(b, m, deterministic)
}
func (m *Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point.Merge(m, src)
}
func (m *Point) XXX_Size() int {
	return xxx_messageInfo_Point.Size(m)
}
func (m *Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Point proto.InternalMessageInfo

func (m *Point) GetLatitude() int32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Point) GetLongitude() int32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Rectangle struct {
	Lo                   *Point   `protobuf:"bytes,1,opt,name=lo,proto3" json:"lo,omitempty"`
	Hi                   *Point   `protobuf:"bytes,2,opt,name=hi,proto3" json:"hi,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rectangle) Reset()         { *m = Rectangle{} }
func (m *Rectangle) String() string { return proto.CompactTextString(m) }
func (*Rectangle) ProtoMessage()    {}
func (*Rectangle) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{10}
}

func (m *Rectangle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rectangle.Unmarshal(m, b)
}
func (m *Rectangle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rectangle.Marshal(b, m, deterministic)
}
func (m *Rectangle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rectangle.Merge(m, src)
}
func (m *Rectangle) XXX_Size() int {
	return xxx_messageInfo_Rectangle.Size(m)
}
func (m *Rectangle) XXX_DiscardUnknown() {
	xxx_messageInfo_Rectangle.DiscardUnknown(m)
}

var xxx_messageInfo_Rectangle proto.InternalMessageInfo

func (m *Rectangle) GetLo() *Point {
	if m != nil {
		return m.Lo
	}
	return nil
}

func (m *Rectangle) GetHi() *Point {
	if m != nil {
		return m.Hi
	}
	return nil
}

type Feature struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Location             *Point   `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{11}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

type RouteNote struct {
	Location             *Point   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteNote) Reset()         { *m = RouteNote{} }
func (m *RouteNote) String() string { return proto.CompactTextString(m) }
func (*RouteNote) ProtoMessage()    {}
func (*RouteNote) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{12}
}

func (m *RouteNote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteNote.Unmarshal(m, b)
}
func (m *RouteNote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteNote.Marshal(b, m, deterministic)
}
func (m *RouteNote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteNote.Merge(m, src)
}
func (m *RouteNote) XXX_Size() int {
	return xxx_messageInfo_RouteNote.Size(m)
}
func (m *RouteNote) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteNote.DiscardUnknown(m)
}

var xxx_messageInfo_RouteNote proto.InternalMessageInfo

func (m *RouteNote) GetLocation() *Point {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *RouteNote) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RouteSummary struct {
	PointCount           int32    `protobuf:"varint,1,opt,name=point_count,json=pointCount,proto3" json:"point_count,omitempty"`
	FeatureCount         int32    `protobuf:"varint,2,opt,name=feature_count,json=featureCount,proto3" json:"feature_count,omitempty"`
	Distance             int32    `protobuf:"varint,3,opt,name=distance,proto3" json:"distance,omitempty"`
	ElapsedTime          int32    `protobuf:"varint,4,opt,name=elapsed_time,json=elapsedTime,proto3" json:"elapsed_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteSummary) Reset()         { *m = RouteSummary{} }
func (m *RouteSummary) String() string { return proto.CompactTextString(m) }
func (*RouteSummary) ProtoMessage()    {}
func (*RouteSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{13}
}

func (m *RouteSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteSummary.Unmarshal(m, b)
}
func (m *RouteSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteSummary.Marshal(b, m, deterministic)
}
func (m *RouteSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteSummary.Merge(m, src)
}
func (m *RouteSummary) XXX_Size() int {
	return xxx_messageInfo_RouteSummary.Size(m)
}
func (m *RouteSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteSummary.DiscardUnknown(m)
}

var xxx_messageInfo_RouteSummary proto.InternalMessageInfo

func (m *RouteSummary) GetPointCount() int32 {
	if m != nil {
		return m.PointCount
	}
	return 0
}

func (m *RouteSummary) GetFeatureCount() int32 {
	if m != nil {
		return m.FeatureCount
	}
	return 0
}

func (m *RouteSummary) GetDistance() int32 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *RouteSummary) GetElapsedTime() int32 {
	if m != nil {
		return m.ElapsedTime
	}
	return 0
}

type EmptyParameters struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParameters) Reset()         { *m = EmptyParameters{} }
func (m *EmptyParameters) String() string { return proto.CompactTextString(m) }
func (*EmptyParameters) ProtoMessage()    {}
func (*EmptyParameters) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{14}
}

func (m *EmptyParameters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParameters.Unmarshal(m, b)
}
func (m *EmptyParameters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParameters.Marshal(b, m, deterministic)
}
func (m *EmptyParameters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParameters.Merge(m, src)
}
func (m *EmptyParameters) XXX_Size() int {
	return xxx_messageInfo_EmptyParameters.Size(m)
}
func (m *EmptyParameters) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParameters.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParameters proto.InternalMessageInfo

type FashionCategory struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ImageUrl             string   `protobuf:"bytes,4,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FashionCategory) Reset()         { *m = FashionCategory{} }
func (m *FashionCategory) String() string { return proto.CompactTextString(m) }
func (*FashionCategory) ProtoMessage()    {}
func (*FashionCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{15}
}

func (m *FashionCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FashionCategory.Unmarshal(m, b)
}
func (m *FashionCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FashionCategory.Marshal(b, m, deterministic)
}
func (m *FashionCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FashionCategory.Merge(m, src)
}
func (m *FashionCategory) XXX_Size() int {
	return xxx_messageInfo_FashionCategory.Size(m)
}
func (m *FashionCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_FashionCategory.DiscardUnknown(m)
}

var xxx_messageInfo_FashionCategory proto.InternalMessageInfo

func (m *FashionCategory) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *FashionCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FashionCategory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FashionCategory) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{16}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserInfo             *Account `protobuf:"bytes,2,opt,name=user_info,json=userInfo,proto3" json:"user_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{17}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginResponse) GetUserInfo() *Account {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "v1.Account")
	proto.RegisterType((*Request)(nil), "v1.Request")
	proto.RegisterType((*Response)(nil), "v1.Response")
	proto.RegisterType((*HomeRequest)(nil), "v1.HomeRequest")
	proto.RegisterType((*HomeResponse)(nil), "v1.HomeResponse")
	proto.RegisterType((*RegisterRequest)(nil), "v1.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "v1.RegisterResponse")
	proto.RegisterType((*GetAllRequest)(nil), "v1.GetAllRequest")
	proto.RegisterType((*GetAllResponse)(nil), "v1.GetAllResponse")
	proto.RegisterType((*Point)(nil), "v1.Point")
	proto.RegisterType((*Rectangle)(nil), "v1.Rectangle")
	proto.RegisterType((*Feature)(nil), "v1.Feature")
	proto.RegisterType((*RouteNote)(nil), "v1.RouteNote")
	proto.RegisterType((*RouteSummary)(nil), "v1.RouteSummary")
	proto.RegisterType((*EmptyParameters)(nil), "v1.EmptyParameters")
	proto.RegisterType((*FashionCategory)(nil), "v1.FashionCategory")
	proto.RegisterType((*LoginRequest)(nil), "v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "v1.LoginResponse")
}

func init() { proto.RegisterFile("profile-service.proto", fileDescriptor_916a1dca15719595) }

var fileDescriptor_916a1dca15719595 = []byte{
	// 1090 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0xdf, 0x6e, 0xdc, 0xc4,
	0x17, 0xae, 0xbd, 0xd9, 0x26, 0x7b, 0xbc, 0x69, 0xd2, 0xf9, 0xb5, 0xfa, 0x6d, 0x4d, 0x51, 0x5d,
	0x23, 0x50, 0x54, 0xb5, 0xbb, 0x49, 0xa8, 0x40, 0x2a, 0x42, 0x22, 0xf4, 0x1f, 0x95, 0xa2, 0x50,
	0xb9, 0x2d, 0xb7, 0xd1, 0xc4, 0x3e, 0xeb, 0x9d, 0x62, 0xcf, 0x98, 0x99, 0x71, 0x4a, 0x6f, 0x79,
	0x04, 0x7a, 0xc7, 0x4b, 0x20, 0x71, 0xc1, 0x23, 0xf0, 0x02, 0xbc, 0x02, 0x0f, 0x82, 0xe6, 0x8f,
	0x13, 0x6f, 0xa2, 0x28, 0xe2, 0x6a, 0xf7, 0x7c, 0xe7, 0x3b, 0xc7, 0x67, 0xce, 0x9c, 0xf3, 0xd9,
	0x70, 0xb3, 0x91, 0x62, 0xce, 0x2a, 0x7c, 0xa0, 0x50, 0x1e, 0xb3, 0x1c, 0xa7, 0x8d, 0x14, 0x5a,
	0x90, 0xf0, 0x78, 0x27, 0xbe, 0x53, 0x0a, 0x51, 0x56, 0x38, 0xb3, 0xc8, 0x51, 0x3b, 0x9f, 0x69,
	0x56, 0xa3, 0xd2, 0xb4, 0x6e, 0x1c, 0x29, 0xbe, 0xed, 0x09, 0xb4, 0x61, 0x33, 0xca, 0xb9, 0xd0,
	0x54, 0x33, 0xc1, 0x95, 0xf7, 0xde, 0xb7, 0x3f, 0xf9, 0x83, 0x12, 0xf9, 0x03, 0xf5, 0x8e, 0x96,
	0x25, 0xca, 0x99, 0x68, 0x2c, 0xe3, 0x3c, 0x3b, 0xfd, 0x7d, 0x00, 0xab, 0x7b, 0x79, 0x2e, 0x5a,
	0xae, 0xc9, 0x35, 0x08, 0x59, 0x31, 0x09, 0x92, 0x60, 0x6b, 0x94, 0x85, 0xac, 0x20, 0x37, 0x60,
	0x88, 0x35, 0x65, 0xd5, 0x24, 0xb4, 0x90, 0x33, 0xc8, 0xc7, 0x00, 0x73, 0x26, 0x95, 0x3e, 0xe4,
	0xb4, 0xc6, 0xc9, 0xc0, 0xba, 0x46, 0x16, 0x39, 0xa0, 0x35, 0x92, 0x8f, 0x60, 0x54, 0xd1, 0xce,
	0xbb, 0x62, 0xbd, 0x6b, 0x06, 0xb0, 0xce, 0xbb, 0x30, 0x6e, 0x16, 0x82, 0xe3, 0x21, 0x6f, 0xeb,
	0x23, 0x94, 0x93, 0xa1, 0xf5, 0x47, 0x16, 0x3b, 0xb0, 0x90, 0x89, 0x6f, 0x15, 0x4a, 0x17, 0x7f,
	0xd5, 0xc5, 0x1b, 0xc0, 0xc6, 0xc7, 0xb0, 0xd6, 0x50, 0xa5, 0xde, 0x09, 0x59, 0x4c, 0x56, 0x9d,
	0xaf, 0xb3, 0x4d, 0x5d, 0xf4, 0x98, 0x6a, 0x2a, 0x0f, 0x5b, 0x59, 0x4d, 0xd6, 0x5c, 0x5d, 0x0e,
	0x79, 0x23, 0x2b, 0x93, 0xb7, 0x16, 0x12, 0x0f, 0x19, 0x9f, 0x8b, 0xc9, 0xc8, 0xc5, 0x1a, 0xe0,
	0x05, 0x9f, 0x0b, 0x72, 0x1f, 0x06, 0x85, 0x38, 0x9a, 0x40, 0x12, 0x6c, 0x45, 0xbb, 0xf1, 0xd4,
	0xf5, 0x77, 0xda, 0x5d, 0xc0, 0xf4, 0x75, 0x77, 0x01, 0x99, 0xa1, 0x91, 0xaf, 0x61, 0x9c, 0x4b,
	0xa4, 0x1a, 0x8b, 0x43, 0x73, 0x35, 0x93, 0xe8, 0xd2, 0xb0, 0xc8, 0xf3, 0x0d, 0x62, 0xc2, 0xdb,
	0xa6, 0x38, 0x0d, 0x1f, 0x5f, 0x1e, 0xee, 0xf9, 0x06, 0x49, 0x47, 0xb0, 0x9a, 0xe1, 0x4f, 0x2d,
	0x2a, 0x9d, 0x02, 0xac, 0x65, 0xa8, 0x1a, 0xc1, 0x15, 0xa6, 0x77, 0x20, 0xfa, 0x4e, 0xd4, 0xe8,
	0x5d, 0x64, 0x13, 0x06, 0xb4, 0x61, 0xfe, 0x32, 0xcd, 0xdf, 0x74, 0x0b, 0xc6, 0x8e, 0xe0, 0x02,
	0xc8, 0x04, 0x56, 0x6b, 0x54, 0x8a, 0x96, 0xe8, 0x59, 0x9d, 0x99, 0xbe, 0x82, 0x8d, 0x0c, 0x4b,
	0xa6, 0x34, 0xca, 0x0b, 0xd3, 0x91, 0x29, 0x8c, 0xa9, 0x9b, 0x1b, 0xd7, 0xd2, 0xd0, 0x9e, 0x22,
	0x9a, 0x1e, 0xef, 0x4c, 0xfd, 0x3c, 0x65, 0x91, 0x27, 0x98, 0x16, 0xa7, 0x6f, 0x61, 0xf3, 0x34,
	0xa9, 0x2f, 0xe1, 0x7c, 0xd6, 0x1b, 0x30, 0xd4, 0xe2, 0x47, 0xe4, 0xdd, 0xc8, 0x59, 0xe3, 0xdc,
	0xb3, 0x06, 0x97, 0x3c, 0xeb, 0x2e, 0xac, 0x3f, 0x47, 0xbd, 0x57, 0x55, 0x17, 0x77, 0x23, 0x83,
	0x6b, 0x1d, 0xe5, 0xc2, 0x62, 0xfe, 0xeb, 0x11, 0xf7, 0x60, 0xf8, 0x52, 0x30, 0xae, 0xcd, 0x98,
	0x56, 0x54, 0x33, 0xdd, 0x16, 0xae, 0xb7, 0xc3, 0xec, 0xc4, 0x26, 0xb7, 0x61, 0x54, 0x09, 0x5e,
	0x3a, 0x67, 0x68, 0x9d, 0xa7, 0x40, 0xba, 0x07, 0xa3, 0x0c, 0x73, 0x4d, 0x79, 0x59, 0x21, 0xb9,
	0x05, 0x61, 0x25, 0x6c, 0x82, 0x68, 0x77, 0x64, 0x9e, 0x6a, 0xb3, 0x67, 0x61, 0x25, 0x8c, 0x6b,
	0xc1, 0x7c, 0x41, 0x7d, 0xd7, 0x82, 0xa5, 0x4f, 0x60, 0xf5, 0x19, 0x52, 0xdd, 0x4a, 0x24, 0x04,
	0x56, 0xec, 0x1a, 0xb9, 0x33, 0xd9, 0xff, 0xe4, 0x53, 0x58, 0xab, 0x44, 0x6e, 0x35, 0xe0, 0x7c,
	0xfc, 0x89, 0x2b, 0xdd, 0x87, 0x51, 0x26, 0x5a, 0x8d, 0x07, 0x42, 0x2f, 0xc7, 0x04, 0x17, 0xc6,
	0xf4, 0x27, 0x2a, 0x5c, 0x9e, 0xa8, 0x0f, 0x01, 0x8c, 0x6d, 0xba, 0x57, 0x6d, 0x5d, 0x53, 0xf9,
	0x9e, 0xdc, 0x81, 0xa8, 0x31, 0xd1, 0x87, 0xb6, 0x7b, 0xbe, 0x49, 0x60, 0xa1, 0xc7, 0x56, 0x8b,
	0x3e, 0x81, 0xf5, 0xb9, 0x3b, 0x85, 0xa7, 0xb8, 0x56, 0x8d, 0x3d, 0xe8, 0x48, 0x31, 0xac, 0x15,
	0x4c, 0x69, 0xca, 0x73, 0x27, 0x44, 0xc3, 0xec, 0xc4, 0x36, 0x52, 0x83, 0x15, 0x6d, 0x54, 0xb7,
	0x65, 0x2b, 0xd6, 0x1f, 0x79, 0xcc, 0x6e, 0xd2, 0x75, 0xd8, 0x78, 0x5a, 0x37, 0xfa, 0xfd, 0x4b,
	0x2a, 0x69, 0x8d, 0x1a, 0xa5, 0x4a, 0x35, 0x6c, 0x3c, 0xa3, 0x6a, 0xc1, 0x04, 0x7f, 0x4c, 0x35,
	0x96, 0x42, 0xbe, 0xef, 0xa9, 0xe2, 0xd0, 0xaa, 0x62, 0xd7, 0xd4, 0xb0, 0xd7, 0xd4, 0x04, 0xa2,
	0x02, 0x55, 0x2e, 0x99, 0xd5, 0x59, 0x2f, 0x8a, 0x7d, 0xc8, 0xc8, 0x0f, 0xab, 0x69, 0x89, 0x56,
	0x9c, 0xbc, 0x2c, 0x5a, 0xe0, 0x8d, 0xac, 0xd2, 0x67, 0x30, 0xde, 0x17, 0x25, 0xe3, 0xdd, 0xb8,
	0xc6, 0x60, 0x25, 0xaf, 0x77, 0x77, 0x27, 0xf6, 0x92, 0x04, 0x86, 0xcb, 0x12, 0x98, 0x7e, 0x0f,
	0xeb, 0x3e, 0x8f, 0x9f, 0xe9, 0x93, 0x75, 0x0a, 0xfa, 0xeb, 0xb4, 0xe5, 0x25, 0xf6, 0xa2, 0xa1,
	0xb6, 0x0f, 0x33, 0x13, 0xbd, 0xfb, 0xd7, 0x00, 0xae, 0xbd, 0x74, 0x2f, 0xaa, 0x57, 0xee, 0x3d,
	0x45, 0xbe, 0x80, 0x15, 0x23, 0x23, 0x64, 0xc3, 0x44, 0xf4, 0x14, 0x27, 0xde, 0x3c, 0x05, 0xbc,
	0x24, 0x45, 0xbf, 0xfc, 0xfd, 0xcf, 0x87, 0x70, 0x48, 0x06, 0xb3, 0xe3, 0x1d, 0x72, 0x60, 0xb4,
	0xca, 0xed, 0x3f, 0xf9, 0x9f, 0xa1, 0x9e, 0x91, 0x98, 0xf8, 0xc6, 0x32, 0xe8, 0x73, 0xfc, 0xdf,
	0xe6, 0xb8, 0x9e, 0x8e, 0x67, 0xc7, 0x3b, 0x33, 0xe9, 0xbd, 0x8f, 0x82, 0x7b, 0xe4, 0x3e, 0x0c,
	0xed, 0x59, 0x89, 0x7d, 0x6e, 0xbf, 0x7d, 0xf1, 0xf5, 0x1e, 0xe2, 0x1b, 0xf1, 0x19, 0xc0, 0x73,
	0xd4, 0xdd, 0x5e, 0x9c, 0x4e, 0x6f, 0x6c, 0x0f, 0xee, 0xf1, 0xf4, 0x8a, 0x59, 0xf9, 0x7d, 0xa6,
	0x3a, 0xa2, 0x22, 0xeb, 0xae, 0x28, 0xbf, 0x91, 0x67, 0xd8, 0xdb, 0x01, 0x99, 0x42, 0x94, 0x61,
	0x2e, 0x64, 0x61, 0xa7, 0xbb, 0x9f, 0xd8, 0x96, 0xd5, 0x9f, 0xf9, 0xf4, 0xca, 0x56, 0x40, 0x66,
	0x7e, 0xad, 0x1e, 0x2f, 0xa8, 0xf6, 0xc9, 0xbb, 0x2d, 0x8b, 0x97, 0x4d, 0x43, 0xdf, 0x0e, 0xc8,
	0x53, 0xb8, 0x69, 0x0b, 0x5a, 0x1a, 0x4a, 0x86, 0xca, 0xf5, 0xf0, 0xcc, 0xf8, 0xc6, 0x16, 0x3c,
	0x33, 0xc0, 0xa6, 0xce, 0x6f, 0xff, 0x0c, 0x7e, 0xdd, 0xfb, 0x23, 0x20, 0xfb, 0x30, 0x7e, 0x2d,
	0x9e, 0x88, 0xc4, 0x7f, 0x74, 0xa4, 0x5f, 0xc2, 0x2d, 0xff, 0x1d, 0xd2, 0x41, 0xc9, 0x5c, 0xc8,
	0xe4, 0x87, 0x17, 0x07, 0x2f, 0x9e, 0xc4, 0x71, 0xb3, 0xa0, 0x35, 0xe5, 0x0b, 0xdd, 0x52, 0x9e,
	0x4b, 0xa1, 0xd4, 0x37, 0xa5, 0xf9, 0x00, 0x98, 0xe6, 0xa2, 0xde, 0x1d, 0xec, 0x4c, 0xb7, 0xef,
	0x05, 0xc1, 0xee, 0x26, 0x6d, 0x9a, 0x8a, 0xb9, 0xfd, 0x9f, 0xbd, 0x55, 0x82, 0x3f, 0x3a, 0x87,
	0x64, 0x5f, 0xc1, 0xe0, 0xe1, 0xf6, 0x43, 0xf2, 0x10, 0xee, 0x65, 0xa8, 0x5b, 0xc9, 0xb1, 0x48,
	0xde, 0x2d, 0x90, 0x27, 0x7a, 0x81, 0x89, 0x44, 0x25, 0x5a, 0x99, 0x63, 0x52, 0x08, 0x54, 0x09,
	0x17, 0x3a, 0xc1, 0x9f, 0x99, 0xd2, 0x53, 0x72, 0x15, 0x56, 0x7e, 0x0b, 0x83, 0xd5, 0xa3, 0xab,
	0xf6, 0x75, 0xf8, 0xf9, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x6a, 0x28, 0x39, 0x30, 0x09,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	Home(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*HomeResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Immediately returns feature of a request
	GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error)
	// Splits a stream of rectangles and returns each feature in a stream of rectangles
	ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (ProfileService_ListFeaturesClient, error)
	//
	RecordRoute(ctx context.Context, opts ...grpc.CallOption) (ProfileService_RecordRouteClient, error)
	RouteChat(ctx context.Context, opts ...grpc.CallOption) (ProfileService_RouteChatClient, error)
	ListFashionCategories(ctx context.Context, in *EmptyParameters, opts ...grpc.CallOption) (ProfileService_ListFashionCategoriesClient, error)
}

type profileServiceClient struct {
	cc *grpc.ClientConn
}

func NewProfileServiceClient(cc *grpc.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Home(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*HomeResponse, error) {
	out := new(HomeResponse)
	err := c.cc.Invoke(ctx, "/v1.ProfileService/Home", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/v1.ProfileService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/v1.ProfileService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetFeature(ctx context.Context, in *Point, opts ...grpc.CallOption) (*Feature, error) {
	out := new(Feature)
	err := c.cc.Invoke(ctx, "/v1.ProfileService/GetFeature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ListFeatures(ctx context.Context, in *Rectangle, opts ...grpc.CallOption) (ProfileService_ListFeaturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[0], "/v1.ProfileService/ListFeatures", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceListFeaturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_ListFeaturesClient interface {
	Recv() (*Feature, error)
	grpc.ClientStream
}

type profileServiceListFeaturesClient struct {
	grpc.ClientStream
}

func (x *profileServiceListFeaturesClient) Recv() (*Feature, error) {
	m := new(Feature)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profileServiceClient) RecordRoute(ctx context.Context, opts ...grpc.CallOption) (ProfileService_RecordRouteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[1], "/v1.ProfileService/RecordRoute", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceRecordRouteClient{stream}
	return x, nil
}

type ProfileService_RecordRouteClient interface {
	Send(*Point) error
	CloseAndRecv() (*RouteSummary, error)
	grpc.ClientStream
}

type profileServiceRecordRouteClient struct {
	grpc.ClientStream
}

func (x *profileServiceRecordRouteClient) Send(m *Point) error {
	return x.ClientStream.SendMsg(m)
}

func (x *profileServiceRecordRouteClient) CloseAndRecv() (*RouteSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RouteSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profileServiceClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (ProfileService_RouteChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[2], "/v1.ProfileService/RouteChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceRouteChatClient{stream}
	return x, nil
}

type ProfileService_RouteChatClient interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ClientStream
}

type profileServiceRouteChatClient struct {
	grpc.ClientStream
}

func (x *profileServiceRouteChatClient) Send(m *RouteNote) error {
	return x.ClientStream.SendMsg(m)
}

func (x *profileServiceRouteChatClient) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profileServiceClient) ListFashionCategories(ctx context.Context, in *EmptyParameters, opts ...grpc.CallOption) (ProfileService_ListFashionCategoriesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[3], "/v1.ProfileService/ListFashionCategories", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceListFashionCategoriesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_ListFashionCategoriesClient interface {
	Recv() (*FashionCategory, error)
	grpc.ClientStream
}

type profileServiceListFashionCategoriesClient struct {
	grpc.ClientStream
}

func (x *profileServiceListFashionCategoriesClient) Recv() (*FashionCategory, error) {
	m := new(FashionCategory)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	Home(context.Context, *HomeRequest) (*HomeResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Immediately returns feature of a request
	GetFeature(context.Context, *Point) (*Feature, error)
	// Splits a stream of rectangles and returns each feature in a stream of rectangles
	ListFeatures(*Rectangle, ProfileService_ListFeaturesServer) error
	//
	RecordRoute(ProfileService_RecordRouteServer) error
	RouteChat(ProfileService_RouteChatServer) error
	ListFashionCategories(*EmptyParameters, ProfileService_ListFashionCategoriesServer) error
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) Home(ctx context.Context, req *HomeRequest) (*HomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Home not implemented")
}
func (*UnimplementedProfileServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (*UnimplementedProfileServiceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedProfileServiceServer) GetFeature(ctx context.Context, req *Point) (*Feature, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFeature not implemented")
}
func (*UnimplementedProfileServiceServer) ListFeatures(req *Rectangle, srv ProfileService_ListFeaturesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFeatures not implemented")
}
func (*UnimplementedProfileServiceServer) RecordRoute(srv ProfileService_RecordRouteServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordRoute not implemented")
}
func (*UnimplementedProfileServiceServer) RouteChat(srv ProfileService_RouteChatServer) error {
	return status.Errorf(codes.Unimplemented, "method RouteChat not implemented")
}
func (*UnimplementedProfileServiceServer) ListFashionCategories(req *EmptyParameters, srv ProfileService_ListFashionCategoriesServer) error {
	return status.Errorf(codes.Unimplemented, "method ListFashionCategories not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_Home_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Home(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProfileService/Home",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Home(ctx, req.(*HomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProfileService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProfileService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetFeature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Point)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetFeature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProfileService/GetFeature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetFeature(ctx, req.(*Point))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ListFeatures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Rectangle)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).ListFeatures(m, &profileServiceListFeaturesServer{stream})
}

type ProfileService_ListFeaturesServer interface {
	Send(*Feature) error
	grpc.ServerStream
}

type profileServiceListFeaturesServer struct {
	grpc.ServerStream
}

func (x *profileServiceListFeaturesServer) Send(m *Feature) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfileService_RecordRoute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProfileServiceServer).RecordRoute(&profileServiceRecordRouteServer{stream})
}

type ProfileService_RecordRouteServer interface {
	SendAndClose(*RouteSummary) error
	Recv() (*Point, error)
	grpc.ServerStream
}

type profileServiceRecordRouteServer struct {
	grpc.ServerStream
}

func (x *profileServiceRecordRouteServer) SendAndClose(m *RouteSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *profileServiceRecordRouteServer) Recv() (*Point, error) {
	m := new(Point)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProfileService_RouteChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProfileServiceServer).RouteChat(&profileServiceRouteChatServer{stream})
}

type ProfileService_RouteChatServer interface {
	Send(*RouteNote) error
	Recv() (*RouteNote, error)
	grpc.ServerStream
}

type profileServiceRouteChatServer struct {
	grpc.ServerStream
}

func (x *profileServiceRouteChatServer) Send(m *RouteNote) error {
	return x.ServerStream.SendMsg(m)
}

func (x *profileServiceRouteChatServer) Recv() (*RouteNote, error) {
	m := new(RouteNote)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ProfileService_ListFashionCategories_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyParameters)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).ListFashionCategories(m, &profileServiceListFashionCategoriesServer{stream})
}

type ProfileService_ListFashionCategoriesServer interface {
	Send(*FashionCategory) error
	grpc.ServerStream
}

type profileServiceListFashionCategoriesServer struct {
	grpc.ServerStream
}

func (x *profileServiceListFashionCategoriesServer) Send(m *FashionCategory) error {
	return x.ServerStream.SendMsg(m)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Home",
			Handler:    _ProfileService_Home_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ProfileService_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _ProfileService_Login_Handler,
		},
		{
			MethodName: "GetFeature",
			Handler:    _ProfileService_GetFeature_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListFeatures",
			Handler:       _ProfileService_ListFeatures_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordRoute",
			Handler:       _ProfileService_RecordRoute_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _ProfileService_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ListFashionCategories",
			Handler:       _ProfileService_ListFashionCategories_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "profile-service.proto",
}
