// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile-service.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string               `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	FirstName            string               `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	PhoneNumber          string               `protobuf:"bytes,5,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	UserName             string               `protobuf:"bytes,6,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string               `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	AvatarUrl            string               `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Dob                  *timestamp.Timestamp `protobuf:"bytes,9,opt,name=dob,proto3" json:"dob,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,10,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdatedTime          *timestamp.Timestamp `protobuf:"bytes,11,opt,name=updated_time,json=updatedTime,proto3" json:"updated_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Account) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *Account) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Account) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

func (m *Account) GetDob() *timestamp.Timestamp {
	if m != nil {
		return m.Dob
	}
	return nil
}

func (m *Account) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *Account) GetUpdatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedTime
	}
	return nil
}

type HomeRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeRequest) Reset()         { *m = HomeRequest{} }
func (m *HomeRequest) String() string { return proto.CompactTextString(m) }
func (*HomeRequest) ProtoMessage()    {}
func (*HomeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{1}
}

func (m *HomeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeRequest.Unmarshal(m, b)
}
func (m *HomeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeRequest.Marshal(b, m, deterministic)
}
func (m *HomeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeRequest.Merge(m, src)
}
func (m *HomeRequest) XXX_Size() int {
	return xxx_messageInfo_HomeRequest.Size(m)
}
func (m *HomeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HomeRequest proto.InternalMessageInfo

func (m *HomeRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

type HomeResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HomeResponse) Reset()         { *m = HomeResponse{} }
func (m *HomeResponse) String() string { return proto.CompactTextString(m) }
func (*HomeResponse) ProtoMessage()    {}
func (*HomeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{2}
}

func (m *HomeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HomeResponse.Unmarshal(m, b)
}
func (m *HomeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HomeResponse.Marshal(b, m, deterministic)
}
func (m *HomeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HomeResponse.Merge(m, src)
}
func (m *HomeResponse) XXX_Size() int {
	return xxx_messageInfo_HomeResponse.Size(m)
}
func (m *HomeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HomeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HomeResponse proto.InternalMessageInfo

func (m *HomeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RegisterRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	AccountInfo          *Account `protobuf:"bytes,2,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{3}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RegisterRequest) GetAccountInfo() *Account {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

type RegisterResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	AccountInfo          *Account `protobuf:"bytes,3,opt,name=account_info,json=accountInfo,proto3" json:"account_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_916a1dca15719595, []int{4}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *RegisterResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RegisterResponse) GetAccountInfo() *Account {
	if m != nil {
		return m.AccountInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "v1.Account")
	proto.RegisterType((*HomeRequest)(nil), "v1.HomeRequest")
	proto.RegisterType((*HomeResponse)(nil), "v1.HomeResponse")
	proto.RegisterType((*RegisterRequest)(nil), "v1.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "v1.RegisterResponse")
}

func init() { proto.RegisterFile("profile-service.proto", fileDescriptor_916a1dca15719595) }

var fileDescriptor_916a1dca15719595 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0x49, 0xcb, 0x92, 0x96, 0x82, 0xad, 0x6e, 0x5d, 0x94, 0x50, 0x5b, 0x98, 0xe5, 0xc9,
	0x30, 0x4c, 0xd2, 0x52, 0x8d, 0x1e, 0x5c, 0x14, 0xa8, 0x8d, 0x1e, 0x92, 0x8b, 0x11, 0xc8, 0xce,
	0x59, 0x58, 0x91, 0x23, 0x6a, 0x6d, 0x72, 0x87, 0xd9, 0x5d, 0xca, 0x39, 0xe7, 0x10, 0x20, 0x39,
	0x3a, 0x97, 0x20, 0x97, 0x3c, 0x54, 0x5e, 0x21, 0x0f, 0x12, 0x70, 0x49, 0xc1, 0x49, 0x84, 0xc4,
	0x39, 0x49, 0xf3, 0xfd, 0x71, 0x38, 0x9c, 0x21, 0xbf, 0x94, 0x12, 0x17, 0x3c, 0x87, 0x50, 0x81,
	0x5c, 0xf1, 0x04, 0xa2, 0x52, 0xa2, 0x46, 0x6a, 0xaf, 0xc6, 0xa3, 0xfd, 0x0c, 0x31, 0xcb, 0x21,
	0x36, 0xc8, 0xbc, 0x5a, 0xc4, 0x9a, 0x17, 0xa0, 0x34, 0x2b, 0xca, 0x46, 0x34, 0xfa, 0xbd, 0x15,
	0xb0, 0x92, 0xc7, 0x4c, 0x08, 0xd4, 0x4c, 0x73, 0x14, 0xaa, 0x65, 0x8f, 0xcc, 0x4f, 0x12, 0x66,
	0x20, 0x42, 0x75, 0xcb, 0xb2, 0x0c, 0x64, 0x8c, 0xa5, 0x51, 0x6c, 0xaa, 0x83, 0x3b, 0x87, 0x74,
	0xcf, 0x92, 0x04, 0x2b, 0xa1, 0xe9, 0x0e, 0xb1, 0x79, 0xea, 0x59, 0xbe, 0x75, 0xd0, 0x9f, 0xda,
	0x3c, 0xa5, 0x7b, 0xa4, 0x03, 0x05, 0xe3, 0xb9, 0x67, 0x1b, 0xa8, 0x29, 0xe8, 0x1f, 0x84, 0x2c,
	0xb8, 0x54, 0x7a, 0x26, 0x58, 0x01, 0x9e, 0x63, 0xa8, 0xbe, 0x41, 0x2e, 0x58, 0x01, 0xf4, 0x37,
	0xd2, 0xcf, 0xd9, 0x9a, 0xdd, 0x32, 0x6c, 0xaf, 0x06, 0x0c, 0xf9, 0x27, 0x19, 0x94, 0x4b, 0x14,
	0x30, 0x13, 0x55, 0x31, 0x07, 0xe9, 0x75, 0x0c, 0xef, 0x1a, 0xec, 0xc2, 0x40, 0xb5, 0xbf, 0x52,
	0x20, 0x1b, 0xff, 0x76, 0xe3, 0xaf, 0x01, 0xe3, 0x1f, 0x91, 0x5e, 0xc9, 0x94, 0xba, 0x45, 0x99,
	0x7a, 0xdd, 0x86, 0x5b, 0xd7, 0x75, 0x5f, 0x6c, 0xc5, 0x34, 0x93, 0xb3, 0x4a, 0xe6, 0x5e, 0xaf,
	0xe9, 0xab, 0x41, 0x9e, 0xca, 0x9c, 0x1e, 0x11, 0x27, 0xc5, 0xb9, 0xd7, 0xf7, 0xad, 0x03, 0x77,
	0x32, 0x8a, 0x9a, 0x11, 0x46, 0xeb, 0x19, 0x47, 0x57, 0xeb, 0x19, 0x4f, 0x6b, 0x19, 0xfd, 0x97,
	0x0c, 0x12, 0x09, 0x4c, 0x43, 0x3a, 0xab, 0xa7, 0xef, 0x91, 0x07, 0x6d, 0x6e, 0xab, 0xaf, 0x91,
	0xda, 0x5e, 0x95, 0xe9, 0xbd, 0xdd, 0x7d, 0xd8, 0xde, 0xea, 0x6b, 0x24, 0xd8, 0x27, 0xee, 0x23,
	0x2c, 0x60, 0x0a, 0xcf, 0x2a, 0x50, 0x9a, 0x0e, 0x89, 0xc3, 0x4a, 0xde, 0x7e, 0x98, 0xfa, 0x6f,
	0x70, 0x40, 0x06, 0x8d, 0x40, 0x95, 0x28, 0x14, 0x50, 0x8f, 0x74, 0x0b, 0x50, 0x8a, 0x65, 0xd0,
	0xaa, 0xd6, 0x65, 0x70, 0x49, 0x76, 0xa7, 0x90, 0x71, 0xa5, 0x41, 0x7e, 0x33, 0x8e, 0x46, 0x64,
	0xc0, 0x9a, 0x1d, 0x98, 0x71, 0xb1, 0x40, 0xf3, 0xbd, 0xdd, 0x89, 0x1b, 0xad, 0xc6, 0x51, 0xbb,
	0x1b, 0x53, 0xb7, 0x15, 0x3c, 0x16, 0x0b, 0x0c, 0xae, 0xc9, 0xf0, 0x3e, 0xb4, 0x6d, 0x61, 0x33,
	0x75, 0x8f, 0x74, 0x34, 0xde, 0x80, 0x58, 0xaf, 0x8f, 0x29, 0x36, 0x9e, 0xe5, 0x7c, 0xff, 0x59,
	0x93, 0xb7, 0x16, 0xd9, 0x79, 0xd2, 0xdc, 0xca, 0x65, 0x73, 0x2a, 0xf4, 0x6f, 0xb2, 0x55, 0xbf,
	0x3d, 0xdd, 0xad, 0x4d, 0x9f, 0x0d, 0x6a, 0x34, 0xbc, 0x07, 0x9a, 0xae, 0x02, 0xf7, 0xc5, 0x87,
	0x8f, 0x6f, 0xec, 0x0e, 0x75, 0xe2, 0xd5, 0x98, 0x5e, 0x90, 0xde, 0xba, 0x6d, 0xfa, 0x73, 0x2d,
	0xfd, 0x6a, 0x32, 0xa3, 0xbd, 0x2f, 0xc1, 0x36, 0xe3, 0x57, 0x93, 0xf1, 0x53, 0x30, 0x88, 0x57,
	0xe3, 0x58, 0xb6, 0xec, 0xa9, 0x75, 0x78, 0xfe, 0xda, 0xbe, 0x3b, 0x7b, 0x69, 0xd3, 0xf7, 0x16,
	0x19, 0x5c, 0xe1, 0xff, 0xe8, 0xb7, 0xa7, 0x1c, 0xbc, 0xb2, 0x48, 0x9c, 0x61, 0x98, 0xc9, 0x32,
	0x09, 0x97, 0x5a, 0x97, 0xa1, 0x04, 0xa5, 0xc3, 0x82, 0x27, 0x12, 0x5b, 0x49, 0xa8, 0x2b, 0x8d,
	0x92, 0xb3, 0xdc, 0x2f, 0x25, 0x5e, 0x43, 0xa2, 0xe9, 0x79, 0x2d, 0x54, 0xa7, 0x71, 0x9c, 0x71,
	0xbd, 0xac, 0xe6, 0x51, 0x82, 0x45, 0xcc, 0x0a, 0x85, 0x37, 0x98, 0xff, 0x68, 0xd6, 0x88, 0x16,
	0x90, 0xf2, 0xaa, 0xf8, 0xaf, 0xf5, 0xd5, 0x19, 0x13, 0x67, 0x1c, 0x1d, 0x1f, 0x5a, 0xd6, 0x64,
	0xc8, 0xca, 0x32, 0xe7, 0x89, 0xb9, 0xfd, 0xf8, 0x5a, 0xa1, 0x38, 0xdd, 0x40, 0xa6, 0xff, 0x10,
	0xe7, 0xe4, 0xf8, 0x84, 0x9e, 0x90, 0xc3, 0x29, 0xe8, 0x4a, 0x0a, 0x48, 0xfd, 0xdb, 0x25, 0x08,
	0x5f, 0x2f, 0xc1, 0x97, 0xa0, 0xb0, 0x92, 0x09, 0xf8, 0x29, 0x82, 0xf2, 0x05, 0x6a, 0x1f, 0x9e,
	0x73, 0xa5, 0x23, 0xba, 0x4d, 0xb6, 0xde, 0xd9, 0x56, 0x77, 0xbe, 0x6d, 0x96, 0xfa, 0xaf, 0x4f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x16, 0x97, 0xbe, 0xd9, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	Home(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*HomeResponse, error)
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type profileServiceClient struct {
	cc *grpc.ClientConn
}

func NewProfileServiceClient(cc *grpc.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Home(ctx context.Context, in *HomeRequest, opts ...grpc.CallOption) (*HomeResponse, error) {
	out := new(HomeResponse)
	err := c.cc.Invoke(ctx, "/v1.ProfileService/Home", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/v1.ProfileService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	Home(context.Context, *HomeRequest) (*HomeResponse, error)
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) Home(ctx context.Context, req *HomeRequest) (*HomeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Home not implemented")
}
func (*UnimplementedProfileServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_Home_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Home(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProfileService/Home",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Home(ctx, req.(*HomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProfileService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Home",
			Handler:    _ProfileService_Home_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _ProfileService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile-service.proto",
}
